name: Deploy (Reusable)

on:
  workflow_call: {}

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          stable

      - name: Derive path
        id: derive
        run: |
          REPO="${GITHUB_REPOSITORY#*/}"
          echo "path=/opt/$REPO" >> $GITHUB_OUTPUT

      - name: Build (optional)
        run: make build || true

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ vars.OVH_HOST }} \
            "bash -lc 'cd ${{ steps.derive.outputs.path }} && ./scripts/deploy.sh'"