name: Fix SystemD Service

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Fix PiratePlunder systemd service
        run: |
          echo "=== Updating systemd service with correct working directory ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net \
            "echo '[Unit]
          Description=PiratePlunder
          After=network.target
          
          [Service]
          User=deploy
          WorkingDirectory=/opt/PiratePlunder/backend
          EnvironmentFile=/opt/PiratePlunder/.env
          ExecStart=/usr/bin/bash -lc \"cd /opt/PiratePlunder/backend && PORT=3001 npm start\"
          Restart=always
          
          [Install]
          WantedBy=multi-user.target' | sudo tee /etc/systemd/system/PiratePlunder.service"
          
          echo "=== Reloading systemd and starting service ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "sudo systemctl daemon-reload"
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "sudo systemctl restart PiratePlunder.service"
          
          echo "=== Checking final service status ==="
          sleep 5
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "systemctl is-active PiratePlunder.service && echo 'Service is active' || echo 'Service failed'"
          
          echo "=== Testing health endpoint ==="
          sleep 2
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "curl -fsS http://localhost:3001/health && echo 'Health check passed' || echo 'Health check failed'"