name: Fix Deploy Script

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Update deploy script
        run: |
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net \
            "cat > /opt/menagerie/scripts/deploy.sh << 'EOF'
          #!/usr/bin/env bash
          set -euo pipefail
          SERVICE=\"menagerie\"
          ROOT=\"/opt/menagerie\"
          REPO=\"https://github.com/drybrushgames/menagerie.git\"
          
          if [ ! -d \"\$ROOT/.git\" ]; then
            # If directory is not empty, initialize git and add remote
            if [ \"\$(ls -A \$ROOT)\" ]; then
              cd \"\$ROOT\"
              git init
              git remote add origin \"\$REPO\"
              git fetch --all
              git reset --hard origin/main
            else
              git clone \"\$REPO\" \"\$ROOT\"
            fi
          fi
          
          cd \"\$ROOT\"
          git fetch --all
          git reset --hard origin/main
          
          make build || true
          
          if [ -f package.json ]; then
            command -v pnpm >/dev/null 2>&1 && pnpm i --prod || npm ci --omit=dev || npm i --omit=dev
          fi
          
          sudo systemctl restart \${SERVICE}.service || true
          echo \"Deploy OK for \$SERVICE\"
          EOF"
          
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net \
            "chmod +x /opt/menagerie/scripts/deploy.sh"

      - name: Test updated deploy script
        run: |
          echo "=== Testing updated deploy script ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "bash -x /opt/menagerie/scripts/deploy.sh"