name: Force Complete Rebuild

on:
  workflow_dispatch:

jobs:
  force-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Force complete rebuild of PiratePlunder
        run: |
          HOST="vps-0b87e710.tail751d97.ts.net"
          
          echo "=== Stop service before rebuild ==="
          tailscale ssh deploy@$HOST "sudo systemctl stop PiratePlunder.service"
          
          echo "=== Clean old build artifacts ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder && rm -rf backend/dist frontend/dist backend/node_modules frontend/node_modules"
          
          echo "=== Install dependencies with full output ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend && npm install"
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/frontend && npm ci"
          
          echo "=== Build frontend ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/frontend && npm run build"
          
          echo "=== Build backend ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend && npm run build"
          
          echo "=== Copy frontend to backend public ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder && mkdir -p backend/dist/public && cp -r frontend/dist/* backend/dist/public/"
          
          echo "=== Copy AI profiles ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder && cp backend/src/ai-profiles.json backend/dist/"
          
          echo "=== Verify auth routes exist in compiled code ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend/dist && grep -r '/auth' . && echo 'Auth routes found!' || echo 'ERROR: No auth routes in compiled code'"
          
          echo "=== Start service ==="
          tailscale ssh deploy@$HOST "sudo systemctl start PiratePlunder.service"
          
          echo "=== Wait and test ==="
          sleep 15
          tailscale ssh deploy@$HOST "curl -s http://localhost:3001/api/health | head -1"
          tailscale ssh deploy@$HOST "systemctl is-active PiratePlunder.service"