name: Get Service Error Logs

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Fix environment and test service
        run: |
          HOST="vps-0b87e710.tail751d97.ts.net"
          
          echo "=== Stop service to prevent restart loop ==="
          tailscale ssh deploy@$HOST "sudo systemctl stop PiratePlunder.service"
          
          echo -e "\n=== Add missing DATABASE_URL to .env ==="
          tailscale ssh deploy@$HOST "echo 'DATABASE_URL=file:/opt/PiratePlunder/data/pirate.db' >> /opt/PiratePlunder/.env"
          tailscale ssh deploy@$HOST "echo 'NODE_ENV=production' >> /opt/PiratePlunder/.env"
          tailscale ssh deploy@$HOST "echo 'PORT=3001' >> /opt/PiratePlunder/.env"
          
          echo -e "\n=== Create data directory ==="
          tailscale ssh deploy@$HOST "mkdir -p /opt/PiratePlunder/data && chown deploy:deploy /opt/PiratePlunder/data"
          
          echo -e "\n=== Setup database with environment ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend && DATABASE_URL='file:/opt/PiratePlunder/data/pirate.db' npx prisma db push --accept-data-loss"
          
          echo -e "\n=== Copy Prisma client to expected location ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend && cp -r src/generated dist/"
          
          echo -e "\n=== Test manual start ==="
          tailscale ssh deploy@$HOST "cd /opt/PiratePlunder/backend && timeout 10 node dist/server.js || echo 'Test completed'"
          
          echo -e "\n=== Start service ==="
          tailscale ssh deploy@$HOST "sudo systemctl start PiratePlunder.service"
          
          echo -e "\n=== Check final status ==="
          sleep 15
          tailscale ssh deploy@$HOST "systemctl is-active PiratePlunder.service && curl -s http://localhost:3001/api/health"