name: Test PiratePlunder Deployment

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Test PiratePlunder deployment
        run: |
          echo "=== Testing PiratePlunder service ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "systemctl is-active PiratePlunder.service && echo 'Service is active'"
          
          echo "=== Testing health endpoint ==="
          curl -fsS "http://vps-0b87e710.tail751d97.ts.net:3001/health" && echo "Health check successful!"
          
          echo "=== Checking service logs ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "sudo journalctl -u PiratePlunder.service --since '2 minutes ago' --no-pager" || echo "Could not get logs"