name: Test Deploy SSH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale up
        uses: tailscale/github-action@v2
        with:
          oauth-client-id:  ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret:     ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags:             tag:ci
          version:          1.76.1

      - name: Test deploy user SSH
        run: |
          echo "=== Testing deploy user SSH ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "echo 'Deploy SSH works!' && whoami && pwd"

      - name: Test sudo access
        run: |
          echo "=== Testing sudo access ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "sudo whoami"

      - name: Test mkdir command
        run: |
          echo "=== Testing mkdir command ==="
          tailscale ssh deploy@vps-0b87e710.tail751d97.ts.net "sudo mkdir -p /opt/test && sudo chown deploy:deploy /opt/test && ls -la /opt/test"